name: Maestro Test Automation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-maestro-cloud-test:
    runs-on: ubuntu-latest
    
    container:
      image: pradapjackie/maestro:1.39.1 # Use Maestro Docker image
    
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up environment variables
      - name: Set up environment variables
        run: echo "MAESTRO_API_KEY=${{ secrets.MAESTRO_API_KEY }}" >> $GITHUB_ENV
      
      # Run Maestro test
      - name: Run Maestro Cloud Test
        run: |
          maestro cloud --apiKey $MAESTRO_API_KEY .maestro/app-release.apk .maestro/android.yaml
      
      # Post-test action
      - name: After Script - Notify Results
        run: echo "Check the results in the Maestro Console."
