name: Maestro Version Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maestro-version-check:
    runs-on: ubuntu-latest
    container:
      image: pradapjackie/maestro:1.39.1
    steps:
      - name: Check Maestro Version
        run: maestro --version
