name: Simple Job

on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch
  pull_request:  # Runs on pull requests

jobs:
  build:
    runs-on: pradapjackie/maestro:1.39.1

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install maestro
        run: maestro -v

      - name: Run Maestro Cloud Test
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: |
          maestro cloud --apiKey $MAESTRO_API_KEY .maestro/app-release.apk .maestro/android.yaml
