name: Simple Job

on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch
  pull_request:  # Runs on pull requests

jobs:
  build:
    runs-on: ubuntu:20.04

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3


      # Step 4: Run a script (e.g., tests)
      - name: Install Maestro and dependencies
        run: |
          apt-get update
          apt-get install -y wget curl
          wget https://github.com/maestrodev/maestro-cli/releases/download/v1.39.1/maestro-linux-x64-1.39.1.tar.gz
          tar -xvzf maestro-linux-x64-1.39.1.tar.gz
          mv maestro /usr/local/bin/

