name: Maestro Version Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maestro-version-check:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install Maestro and Dependencies
        run: |
          apk add --no-cache openjdk8 curl bash
          curl -L https://get.maestro.mobile.dev | bash
          maestro --version

      - name: Verify Success
        run: echo "Maestro version check completed successfully."
